version: 2
updates:
  - package-ecosystem: composer
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    allow:
      - dependency-type: direct
      - dependency-type: indirect
