version: 2
updates:
  - package-ecosystem: composer
    directory: '/'
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    commit-message:
      prefix: 'chore'
    allow:
      - dependency-type: direct
      - dependency-type: indirect
